const moment = require('moment');
moment().format();
let now = moment().unix();

exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('currencies').del()
    .then(function () {
      // Inserts seed entries
      return Promise.all([
        knex('currencies').insert({ currencyName: 'United Arab Emirates Dirham', currencyCode: 'AED', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Afghanistan Afghani', currencyCode: 'AFN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Albania Lek', currencyCode: 'ALL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Armenia Dram', currencyCode: 'AMD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Netherlands Antilles Guilder', currencyCode: 'ANG', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Angola Kwanza', currencyCode: 'AOA', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Argentina Peso', currencyCode: 'ARS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Australia Dollar', currencyCode: 'AUD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Aruba Guilder', currencyCode: 'AWG', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Azerbaijan New Manat', currencyCode: 'AZN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bosnia and Herzegovina Convertible Marka', currencyCode: 'BAM', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Barbados Dollar', currencyCode: 'BBD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bangladesh Taka', currencyCode: 'BDT', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bulgaria Lev', currencyCode: 'BGN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bahrain Dinar', currencyCode: 'BHD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Burundi Franc', currencyCode: 'BIF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bermuda Dollar', currencyCode: 'BMD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Brunei Darussalam Dollar', currencyCode: 'BND', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bolivia Bolíviano', currencyCode: 'BOB', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Brazil Real', currencyCode: 'BRL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bahamas Dollar', currencyCode: 'BSD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Bhutan Ngultrum', currencyCode: 'BTN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Botswana Pula', currencyCode: 'BWP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Belarus Ruble', currencyCode: 'BYN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Belize Dollar', currencyCode: 'BZD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Canada Dollar', currencyCode: 'CAD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Congo/Kinshasa Franc', currencyCode: 'CDF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Switzerland Franc', currencyCode: 'CHF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Chile Peso', currencyCode: 'CLP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'China Yuan Renminbi', currencyCode: 'CNY', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Colombia Peso', currencyCode: 'COP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Costa Rica Colon', currencyCode: 'CRC', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Cuba Convertible Peso', currencyCode: 'CUC', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Cuba Peso', currencyCode: 'CUP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Cape Verde Escudo', currencyCode: 'CVE', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Czech Republic Koruna', currencyCode: 'CZK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Djibouti Franc', currencyCode: 'DJF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Denmark Krone', currencyCode: 'DKK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Dominican Republic Peso', currencyCode: 'DOP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Algeria Dinar', currencyCode: 'DZD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Egypt Pound', currencyCode: 'EGP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Eritrea Nakfa', currencyCode: 'ERN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Ethiopia Birr', currencyCode: 'ETB', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Euro Member Countries', currencyCode: 'EUR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Fiji Dollar', currencyCode: 'FJD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Falkland Islands (Malvinas) Pound', currencyCode: 'FKP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'United Kingdom Pound', currencyCode: 'GBP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Georgia Lari', currencyCode: 'GEL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Guernsey Pound', currencyCode: 'GGP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Ghana Cedi', currencyCode: 'GHS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Gibraltar Pound', currencyCode: 'GIP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Gambia Dalasi', currencyCode: 'GMD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Guinea Franc', currencyCode: 'GNF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Guatemala Quetzal', currencyCode: 'GTQ', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Guyana Dollar', currencyCode: 'GYD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Hong Kong Dollar', currencyCode: 'HKD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Honduras Lempira', currencyCode: 'HNL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Croatia Kuna', currencyCode: 'HRK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Haiti Gourde', currencyCode: 'HTG', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Hungary Forint', currencyCode: 'HUF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Indonesia Rupiah', currencyCode: 'IDR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Israel Shekel', currencyCode: 'ILS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Isle of Man Pound', currencyCode: 'IMP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'India Rupee', currencyCode: 'INR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Iraq Dinar', currencyCode: 'IQD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Iran Rial', currencyCode: 'IRR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Iceland Krona', currencyCode: 'ISK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Jersey Pound', currencyCode: 'JEP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Jamaica Dollar', currencyCode: 'JMD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Jordan Dinar', currencyCode: 'JOD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Japan Yen', currencyCode: 'JPY', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Kenya Shilling', currencyCode: 'KES', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Kyrgyzstan Som', currencyCode: 'KGS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Cambodia Riel', currencyCode: 'KHR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Comoros Franc', currencyCode: 'KMF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Korea (North) Won', currencyCode: 'KPW', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Korea (South) Won', currencyCode: 'KRW', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Kuwait Dinar', currencyCode: 'KWD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Cayman Islands Dollar', currencyCode: 'KYD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Kazakhstan Tenge', currencyCode: 'KZT', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Laos Kip', currencyCode: 'LAK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Lebanon Pound', currencyCode: 'LBP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Sri Lanka Rupee', currencyCode: 'LKR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Liberia Dollar', currencyCode: 'LRD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Lesotho Loti', currencyCode: 'LSL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Libya Dinar', currencyCode: 'LYD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Morocco Dirham', currencyCode: 'MAD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Moldova Leu', currencyCode: 'MDL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Madagascar Ariary', currencyCode: 'MGA', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Macedonia Denar', currencyCode: 'MKD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Myanmar (Burma) Kyat', currencyCode: 'MMK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Mongolia Tughrik', currencyCode: 'MNT', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Macau Pataca', currencyCode: 'MOP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Mauritania Ouguiya', currencyCode: 'MRO', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Mauritius Rupee', currencyCode: 'MUR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Maldives (Maldive Islands) Rufiyaa', currencyCode: 'MVR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Malawi Kwacha', currencyCode: 'MWK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Mexico Peso', currencyCode: 'MXN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Malaysia Ringgit', currencyCode: 'MYR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Mozambique Metical', currencyCode: 'MZN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Namibia Dollar', currencyCode: 'NAD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Nigeria Naira', currencyCode: 'NGN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Nicaragua Cordoba', currencyCode: 'NIO', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Norway Krone', currencyCode: 'NOK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Nepal Rupee', currencyCode: 'NPR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'New Zealand Dollar', currencyCode: 'NZD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Oman Rial', currencyCode: 'OMR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Panama Balboa', currencyCode: 'PAB', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Peru Sol', currencyCode: 'PEN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Papua New Guinea Kina', currencyCode: 'PGK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Philippines Peso', currencyCode: 'PHP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Pakistan Rupee', currencyCode: 'PKR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Poland Zloty', currencyCode: 'PLN', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Paraguay Guarani', currencyCode: 'PYG', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Qatar Riyal', currencyCode: 'QAR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Romania New Leu', currencyCode: 'RON', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Serbia Dinar', currencyCode: 'RSD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Russia Ruble', currencyCode: 'RUB', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Rwanda Franc', currencyCode: 'RWF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Saudi Arabia Riyal', currencyCode: 'SAR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Solomon Islands Dollar', currencyCode: 'SBD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Seychelles Rupee', currencyCode: 'SCR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Sudan Pound', currencyCode: 'SDG', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Sweden Krona', currencyCode: 'SEK', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Singapore Dollar', currencyCode: 'SGD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Saint Helena Pound', currencyCode: 'SHP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Sierra Leone Leone', currencyCode: 'SLL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Somalia Shilling', currencyCode: 'SOS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Seborga Luigino', currencyCode: 'SPL*', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Suriname Dollar', currencyCode: 'SRD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'São Tomé and Príncipe Dobra', currencyCode: 'STD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'El Salvador Colon', currencyCode: 'SVC', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Syria Pound', currencyCode: 'SYP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Swaziland Lilangeni', currencyCode: 'SZL', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Thailand Baht', currencyCode: 'THB', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Tajikistan Somoni', currencyCode: 'TJS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Turkmenistan Manat', currencyCode: 'TMT', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Tunisia Dinar', currencyCode: 'TND', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: "Tonga Pa'anga", currencyCode: 'TOP', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Turkey Lira', currencyCode: 'TRY', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Trinidad and Tobago Dollar', currencyCode: 'TTD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Tuvalu Dollar', currencyCode: 'TVD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Taiwan New Dollar', currencyCode: 'TWD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Tanzania Shilling', currencyCode: 'TZS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Ukraine Hryvnia', currencyCode: 'UAH', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Uganda Shilling', currencyCode: 'UGX', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'United States Dollar', currencyCode: 'USD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Uruguay Peso', currencyCode: 'UYU', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Uzbekistan Som', currencyCode: 'UZS', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Venezuela Bolivar', currencyCode: 'VEF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Viet Nam Dong', currencyCode: 'VND', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Vanuatu Vatu', currencyCode: 'VUV', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Samoa Tala', currencyCode: 'WST', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Communauté Financière Africaine (BEAC) CFA Franc BEAC', currencyCode: 'XAF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'East Caribbean Dollar', currencyCode: 'XCD', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'International Monetary Fund (IMF) Special Drawing Rights', currencyCode: 'XDR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Communauté Financière Africaine (BCEAO) Franc', currencyCode: 'XOF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Comptoirs Français du Pacifique (CFP) Franc', currencyCode: 'XPF', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Yemen Rial', currencyCode: 'YER', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'South Africa Rand', currencyCode: 'ZAR', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Zambia Kwacha', currencyCode: 'ZMW', createdAt: now, updatedAt: now }),
        knex('currencies').insert({ currencyName: 'Zimbabwe Dollar', currencyCode: 'ZWD', createdAt: now, updatedAt: now }),      ])
    });
};
